feign:
  client:
    config:
      jokeClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
        requestInterceptors: com.marcoscouto.openfeign.InterceptorExample